version: '3.6'

services:
  dns:
    image: sameersbn/bind:latest
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    - "10000:10000/tcp"
    environment:
      ROOT_PASSWORD_FILE: /run/secrets/root_pass
    volumes:
    - data:/data
    secrets:
    - root_pass
secrets:
  root_pass:
    file: ./root_pass.secret
volumes:
  data: {}
